name: Arbitrage Bot (scheduled)

on:
  workflow_dispatch:            # kézzel is indítható az Actions fülön
  schedule:
    - cron: "*/5 * * * *"       # 5 percenként fut

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps

      - name: Run bot once
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          TOTAL_STAKE: ${{ secrets.TOTAL_STAKE }}
          # Alább: sportok vesszővel elválasztva (repo Secrets-ben állítsd be)
          SPORTS: ${{ secrets.SPORTS }}               # pl.: "tenisz,labdarúgás"
          # Opcionális: ha külön szeretnéd kapcsolgatni a Bet365-öt (1 = bekapcsol)
          BET365_ENABLED: ${{ secrets.BET365_ENABLED }} # "0" vagy "1"
        run: |
          . .venv/bin/activate
          python runner.py
