name: Arbitrage Bot (scheduled)

on:
  workflow_dispatch:
  schedule:
    - cron: "*/3 * * * *"   # 3 percenként fut

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps

      - name: Run bot once
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          TOTAL_STAKE: ${{ secrets.TOTAL_STAKE }}
          ONLY_NOTIFY_ON_SUREBETS: ${{ secrets.ONLY_NOTIFY_ON_SUREBETS }}  # "1" (alap) vagy "0"
          VERBOSE: ${{ secrets.VERBOSE }}                                   # "1" = diagnosztika
          # Opcionális URL-listák (vesszővel elválasztva)
          TIPPMIX_URLS: ${{ secrets.TIPPMIX_URLS }}
          VEGAS_URLS: ${{ secrets.VEGAS_URLS }}
          BET365_URLS: ${{ secrets.BET365_URLS }}
        run: |
          . .venv/bin/activate
          python runner.py
